name: SSH Connection Test

on:
  workflow_dispatch:  # This allows manual triggering

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Add host key to known hosts
      run: ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts
        
    - name: Debug SSH connection
      run: ssh -v ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "echo Connection successful"